package hn.edu.ujcv.pdm_2021_ii_p3_proyecto3.backend.constants

object Sql {
    const val SELECT = " SELECT "
    const val UPDATE = " UPDATE "
    const val WHERE = " WHERE "
    const val AND = " AND "
    const val ON = " ON "
    const val FROM = " FROM "
    const val LIKE = " LIKE "
    const val LIMIT = " LIMIT "
    const val OFFSET = " OFFSET "
    const val COLON = ":"
    const val COMMA_COLON = ", :"
    const val EQUAL_COLON = " = :"
    const val EQUALS = " = "
    const val NOT_EQUALS = " != "
    const val LESS_THAN = " < "
    const val PERCENT = "%"
    const val LEFT_PARANTHESIS = "("
    const val RIGHT_PARANTHESIS = ")"
    const val COMMA = ", "
    const val UNION = " UNION "
    const val SINGLE_QUOTE = "'"
    const val DOUBLE_QUOTE = "\""
    const val DUPLICATE_KEY = "DUPLICATE KEY"
    const val IN = " IN "
    const val AS = " AS "
    const val OR = " OR "
    const val DOT = "."
    const val ORDER_BY = " ORDER BY "
    const val ASC = " ASC"
    const val DESC = " DESC"
    const val SET = " SET "
    const val INSERT_INTO = "INSERT INTO "
    const val DELETE_FROM = "DELETE FROM "
    const val CONCATENATION_OPERATOR = " || "
    const val VALUES = " VALUES"
    const val INNER_JOIN = " INNER JOIN "
    const val CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP"
    const val TIMESTAMPDIFF = "TIMESTAMPDIFF"
    const val MINUTE = "MINUTE"
    const val LHS = "LHS"
    const val RHS = "RHS"
    const val GROUP_CONCAT = "GROUP_CONCAT"
    const val GROUP_BY = " GROUP BY "
}